apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aap-shared-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: aap-shared-storage-pv
  storageClassName: ""