---
# This file is called by other roles:
# include_tasks: roles/common/tasks/log_result.yml
# vars: { test_name: '...', status: '...', ... }

- name: Append Result to Central CSV
  delegate_to: localhost
  ansible.builtin.lineinfile:
    path: "{{ csv_report_path }}"
    # Format: RFC, TIMESTAMP, SERVER, TEST, SEVERITY, INST, DB, PORT, DESC, RESULT
    line: >-
      {{ rfc }},{{ hc_timestamp }},{{ inventory_hostname }},{{ test_name }},{{ severity | default('INFO') }},{{ inst_name | default('-') }},{{ db_name | default('-') }},{{ port | default('-') }},{{ description }},{{ status }}
    insertafter: EOF